CREATE TABLE [dbo].["aretum"."assignment_view"] (
    [assignment_type]           INT             NULL,
    [assignment_key]            NVARCHAR (MAX)  NULL,
    [project_customer_key]      BIGINT          NULL,
    [project_customer_code]     NVARCHAR (25)   NULL,
    [project_key]               BIGINT          NULL,
    [project_code]              NVARCHAR (30)   NULL,
    [project_type_key]          BIGINT          NULL,
    [project_status_key]        BIGINT          NULL,
    [project_manager_key]       NVARCHAR (MAX)  NULL,
    [open_edit]                 VARBINARY (MAX) NULL,
    [task_key]                  NVARCHAR (MAX)  NULL,
    [task_name]                 VARBINARY (MAX) NULL,
    [person_customer_key]       BIGINT          NULL,
    [person_customer_code]      NVARCHAR (25)   NULL,
    [person_key]                NVARCHAR (MAX)  NULL,
    [person_active]             NVARCHAR (MAX)  NULL,
    [person_labor_category_key] NVARCHAR (MAX)  NULL,
    [person_labor_category]     NVARCHAR (MAX)  NULL,
    [person_bill_rate]          NVARCHAR (MAX)  NULL,
    [person_cost_rate]          NVARCHAR (MAX)  NULL,
    [person_location_key]       NVARCHAR (MAX)  NULL,
    [person_location]           NVARCHAR (MAX)  NULL,
    [bill_rate]                 NVARCHAR (MAX)  NULL,
    [bill_rate_currency]        NVARCHAR (MAX)  NULL,
    [bill_rate_source]          NVARCHAR (MAX)  NULL,
    [cost_rate]                 NVARCHAR (MAX)  NULL,
    [cost_rate_currency]        NVARCHAR (MAX)  NULL,
    [cost_rate_source]          NVARCHAR (MAX)  NULL,
    [bill_customer_key]         NVARCHAR (MAX)  NULL,
    [bill_customer_code]        NVARCHAR (MAX)  NULL,
    [cost_customer_key]         NVARCHAR (MAX)  NULL,
    [cost_customer_code]        NVARCHAR (MAX)  NULL,
    [labor_category_key]        NVARCHAR (MAX)  NULL,
    [labor_category]            NVARCHAR (MAX)  NULL,
    [location_key]              NVARCHAR (MAX)  NULL,
    [location]                  NVARCHAR (MAX)  NULL,
    [begin_date]                DATETIME2 (6)   NULL,
    [end_date]                  DATETIME2 (6)   NULL,
    [budget_hours]              NVARCHAR (MAX)  NULL,
    [etc_hours]                 NVARCHAR (MAX)  NULL,
    [exceed_budget]             NVARCHAR (MAX)  NULL,
    [use_wbs_dates]             NVARCHAR (MAX)  NULL,
    [cost_struct_labor_key]     NVARCHAR (MAX)  NULL,
    [edc]                       DATETIME2 (6)   NULL,
    [last_etc_update_date]      DATETIME2 (6)   NULL,
    [ic_cost_rate]              NVARCHAR (MAX)  NULL,
    [ic_cost_struct_labor_key]  NVARCHAR (MAX)  NULL
);


GO

