CREATE TABLE [dbo].["aretum"."person"] (
    [person_key]                  BIGINT          NULL,
    [person_code]                 NVARCHAR (25)   NULL,
    [username]                    NVARCHAR (55)   NULL,
    [password]                    NVARCHAR (32)   NULL,
    [password_date]               DATETIME2 (6)   NULL,
    [ssn]                         NVARCHAR (11)   NULL,
    [emp_id]                      NVARCHAR (25)   NULL,
    [first_name]                  NVARCHAR (50)   NULL,
    [last_name]                   NVARCHAR (50)   NULL,
    [middle_initial]              NVARCHAR (1)    NULL,
    [suffix]                      NVARCHAR (10)   NULL,
    [email]                       NVARCHAR (50)   NULL,
    [customer_key]                BIGINT          NULL,
    [pay_code_key]                BIGINT          NULL,
    [hour_increment]              DECIMAL (15, 2) NULL,
    [time_period_key]             BIGINT          NULL,
    [time_vendor_key]             BIGINT          NULL,
    [expense_vendor_key]          BIGINT          NULL,
    [active]                      NVARCHAR (1)    NULL,
    [timesheet_lines]             NVARCHAR (1)    NULL,
    [timesheet_email]             NVARCHAR (1)    NULL,
    [leave_request_email]         NVARCHAR (1)    NULL,
    [expense_email]               NVARCHAR (1)    NULL,
    [hide_vat]                    NVARCHAR (1)    NULL,
    [tito_required]               NVARCHAR (1)    NULL,
    [payment_method_key]          BIGINT          NULL,
    [currency_key]                BIGINT          NULL,
    [expense_approval_amount]     DECIMAL (17, 4) NULL,
    [vehicle_number]              NVARCHAR (32)   NULL,
    [project_key]                 BIGINT          NULL,
    [task_key]                    BIGINT          NULL,
    [labor_category_key]          BIGINT          NULL,
    [business_week_key]           BIGINT          NULL,
    [assignment_email]            NVARCHAR (1)    NULL,
    [hire_date]                   DATETIME2 (6)   NULL,
    [payment_currency_key]        BIGINT          NULL,
    [login_failures]              DECIMAL (3)     NULL,
    [location_key]                BIGINT          NULL,
    [employee_type_key]           BIGINT          NULL,
    [tbd_user]                    NVARCHAR (1)    NULL,
    [user01]                      NVARCHAR (128)  NULL,
    [user02]                      NVARCHAR (128)  NULL,
    [user03]                      NVARCHAR (128)  NULL,
    [user04]                      NVARCHAR (128)  NULL,
    [user05]                      NVARCHAR (128)  NULL,
    [user06]                      NVARCHAR (128)  NULL,
    [user07]                      NVARCHAR (128)  NULL,
    [user08]                      NVARCHAR (128)  NULL,
    [user09]                      NVARCHAR (128)  NULL,
    [user10]                      NVARCHAR (128)  NULL,
    [purchase_email]              NVARCHAR (1)    NULL,
    [user11]                      NVARCHAR (128)  NULL,
    [user12]                      NVARCHAR (128)  NULL,
    [user13]                      NVARCHAR (128)  NULL,
    [user14]                      NVARCHAR (128)  NULL,
    [user15]                      NVARCHAR (128)  NULL,
    [user16]                      NVARCHAR (128)  NULL,
    [user17]                      NVARCHAR (128)  NULL,
    [user18]                      NVARCHAR (128)  NULL,
    [user19]                      NVARCHAR (128)  NULL,
    [user20]                      NVARCHAR (128)  NULL,
    [vendor_invoice_person]       NVARCHAR (1)    NULL,
    [po_form_title]               NVARCHAR (240)  NULL,
    [po_signature_key]            BIGINT          NULL,
    [allow_items]                 NVARCHAR (1)    NULL,
    [purchase_approval_amount]    DECIMAL (17, 4) NULL,
    [subcontractor]               NVARCHAR (1)    NULL,
    [activation_pending]          NVARCHAR (1)    NULL,
    [ar_approval_amount]          DECIMAL (17, 4) NULL,
    [customer_invoice_email]      NVARCHAR (1)    NULL,
    [subk_user_account_activated] NVARCHAR (1)    NULL,
    [integration_user]            NVARCHAR (1)    NULL,
    [created_timestamp]           DATETIME2 (6)   NULL,
    [last_modified_timestamp]     DATETIME2 (6)   NULL,
    [email_verified]              NVARCHAR (1)    NULL,
    [verification_code]           NVARCHAR (2048) NULL,
    [passport_id]                 NVARCHAR (64)   NULL,
    [currency_code_key]           BIGINT          NULL,
    [default_legal_entity_key]    BIGINT          NULL,
    [last_login_timestamp]        DATETIME2 (6)   NULL,
    [integration_user_type]       NVARCHAR (25)   NULL,
    [tito_button_setting]         NVARCHAR (1)    NULL
);


GO

