CREATE TABLE [dbo].["aretum"."prj_periodic_jsr"] (
    [Current Period Hours or Amount]           DECIMAL (15, 2) NULL,
    [Cost Report Item Label]                   NVARCHAR (128)  NULL,
    [Cost Report Item Sequence]                SMALLINT        NULL,
    [Cost Report Item Total Indicator]         VARBINARY (MAX) NULL,
    [Cost Report Name]                         NVARCHAR (128)  NULL,
    [EAC Amount]                               DECIMAL (15, 2) NULL,
    [Fiscal YTD Amount]                        DECIMAL (15, 2) NULL,
    [ITD Amount]                               DECIMAL (15, 2) NULL,
    [Period Begin Date]                        DATETIME2 (6)   NULL,
    [Period End Date]                          DATETIME2 (6)   NULL,
    [Period Type]                              NVARCHAR (32)   NULL,
    [Primary Project Lead - First Name]        NVARCHAR (50)   NULL,
    [Primary Project Lead - Last Name]         NVARCHAR (50)   NULL,
    [Primary Project Lead - Middle Initial]    NVARCHAR (1)    NULL,
    [Primary Project Lead - Username]          NVARCHAR (55)   NULL,
    [Primary Project Manager - First Name]     NVARCHAR (50)   NULL,
    [Primary Project Manager - Last Name]      NVARCHAR (50)   NULL,
    [Primary Project Manager - Middle Initial] NVARCHAR (1)    NULL,
    [Primary Project Manager - Username]       NVARCHAR (55)   NULL,
    [Primary Project Viewer - First Name]      NVARCHAR (50)   NULL,
    [Primary Project Viewer - Last Name]       NVARCHAR (50)   NULL,
    [Primary Project Viewer - Middle Initial]  NVARCHAR (1)    NULL,
    [Primary Project Viewer - Username]        NVARCHAR (55)   NULL,
    [Probability Percent]                      DECIMAL (3)     NULL,
    [Project Active Status]                    NVARCHAR (1)    NULL,
    [Project Billing Type]                     NVARCHAR (25)   NULL,
    [Project Burdened Expense Cost Budget]     DECIMAL (17, 4) NULL,
    [Project Burdened Labor Cost Budget]       DECIMAL (17, 4) NULL,
    [Project Code]                             NVARCHAR (30)   NULL,
    [Project Completed Percent]                DECIMAL (6, 3)  NULL,
    [Project Expense Bill Budget]              DECIMAL (17, 4) NULL,
    [Project Expense Cost Budget]              DECIMAL (17, 4) NULL,
    [Project Funded Cost - Current]            DECIMAL (17, 4) NULL,
    [Project Funded Value - Current]           DECIMAL (17, 4) NULL,
    [Project Hours Budget]                     DECIMAL (15, 2) NULL,
    [Project Key]                              BIGINT          NULL,
    [Project Labor Bill Budget]                DECIMAL (17, 4) NULL,
    [Project Labor Cost Budget]                DECIMAL (17, 4) NULL,
    [Project Org Code]                         NVARCHAR (25)   NULL,
    [Project Org Key]                          BIGINT          NULL,
    [Project Org Name]                         NVARCHAR (128)  NULL,
    [Project Owning Org Code]                  NVARCHAR (25)   NULL,
    [Project Owning Org Key]                   BIGINT          NULL,
    [Project Owning Org Name]                  NVARCHAR (128)  NULL,
    [Project Revised Begin Date]               DATETIME2 (6)   NULL,
    [Project Revised End Date]                 DATETIME2 (6)   NULL,
    [Project Status]                           NVARCHAR (50)   NULL,
    [Project Title]                            NVARCHAR (2000) NULL,
    [Project Total Cost - Current]             DECIMAL (17, 4) NULL,
    [Project Total Fee - Current]              DECIMAL (17, 4) NULL,
    [Project Total Value - Current]            DECIMAL (17, 4) NULL,
    [Row Metrics]                              NVARCHAR (128)  NULL,
    [Task Key]                                 BIGINT          NULL,
    [Task Name]                                NVARCHAR (50)   NULL,
    [Task Number]                              NVARCHAR (128)  NULL,
    [Last Updated]                             DATETIME2 (6)   NULL
);


GO

