CREATE TABLE [dbo].["aretum"."project"] (
    [project_key]                BIGINT          NULL,
    [customer_key]               BIGINT          NULL,
    [owning_customer_key]        BIGINT          NULL,
    [project_code]               NVARCHAR (30)   NULL,
    [account_number]             NVARCHAR (128)  NULL,
    [title]                      NVARCHAR (2000) NULL,
    [purpose]                    NVARCHAR (2000) NULL,
    [pay_code_key]               BIGINT          NULL,
    [project_type_key]           BIGINT          NULL,
    [project_status_key]         BIGINT          NULL,
    [billing_type_key]           BIGINT          NULL,
    [posting_group_key]          BIGINT          NULL,
    [cost_struct_key]            BIGINT          NULL,
    [orig_start_date]            DATETIME2 (6)   NULL,
    [orig_end_date]              DATETIME2 (6)   NULL,
    [rev_start_date]             DATETIME2 (6)   NULL,
    [rev_end_date]               DATETIME2 (6)   NULL,
    [completed_date]             DATETIME2 (6)   NULL,
    [total_value]                DECIMAL (17, 4) NULL,
    [funded_value]               DECIMAL (17, 4) NULL,
    [hours_budget]               DECIMAL (15, 2) NULL,
    [hours_etc]                  DECIMAL (15, 2) NULL,
    [hours_est_tot]              DECIMAL (15, 2) NULL,
    [exp_bill_budget]            DECIMAL (17, 4) NULL,
    [exp_cost_budget]            DECIMAL (17, 4) NULL,
    [exp_cost_burden_budget]     DECIMAL (17, 4) NULL,
    [exp_bill_etc]               DECIMAL (17, 4) NULL,
    [exp_cost_etc]               DECIMAL (17, 4) NULL,
    [exp_bill_est_tot]           DECIMAL (17, 4) NULL,
    [exp_cost_est_tot]           DECIMAL (17, 4) NULL,
    [labor_bill_budget]          DECIMAL (17, 4) NULL,
    [labor_cost_budget]          DECIMAL (17, 4) NULL,
    [labor_cost_burden_budget]   DECIMAL (17, 4) NULL,
    [labor_bill_etc]             DECIMAL (17, 4) NULL,
    [labor_cost_etc]             DECIMAL (17, 4) NULL,
    [labor_bill_est_tot]         DECIMAL (17, 4) NULL,
    [labor_cost_est_tot]         DECIMAL (17, 4) NULL,
    [assignment_flag]            NVARCHAR (1)    NULL,
    [expense_assignment_flag]    NVARCHAR (1)    NULL,
    [time_assignment_flag]       NVARCHAR (1)    NULL,
    [task_level_assignment]      NVARCHAR (1)    NULL,
    [allow_self_plan]            NVARCHAR (1)    NULL,
    [self_assign_plans]          NVARCHAR (1)    NULL,
    [er_task_required]           NVARCHAR (1)    NULL,
    [ts_task_required]           NVARCHAR (1)    NULL,
    [future_charge]              NVARCHAR (1)    NULL,
    [tito_required]              NVARCHAR (1)    NULL,
    [created]                    DATETIME2 (6)   NULL,
    [probability_percent]        DECIMAL (3)     NULL,
    [percent_complete]           DECIMAL (6, 3)  NULL,
    [bill_rate_source]           NVARCHAR (1)    NULL,
    [cost_rate_source]           NVARCHAR (1)    NULL,
    [use_labor_category]         NVARCHAR (1)    NULL,
    [enforce_wbs_dates]          NVARCHAR (1)    NULL,
    [leave_balance]              NVARCHAR (1)    NULL,
    [customer_approves_first]    NVARCHAR (1)    NULL,
    [pct_complete_rule]          NVARCHAR (1)    NULL,
    [project_color]              NVARCHAR (16)   NULL,
    [proj_require_time_comments] NVARCHAR (1)    NULL,
    [location_required]          NVARCHAR (1)    NULL,
    [location_key]               BIGINT          NULL,
    [limit_bill_to_funded]       NVARCHAR (1)    NULL,
    [limit_rev_to_funded]        NVARCHAR (1)    NULL,
    [contract_key]               BIGINT          NULL,
    [total_cost]                 DECIMAL (17, 4) NULL,
    [total_fee]                  DECIMAL (17, 4) NULL,
    [funded_cost]                DECIMAL (17, 4) NULL,
    [funded_fee]                 DECIMAL (17, 4) NULL,
    [orig_total_value]           DECIMAL (17, 4) NULL,
    [orig_total_cost]            DECIMAL (17, 4) NULL,
    [orig_total_fee]             DECIMAL (17, 4) NULL,
    [orig_funded_value]          DECIMAL (17, 4) NULL,
    [orig_funded_cost]           DECIMAL (17, 4) NULL,
    [orig_funded_fee]            DECIMAL (17, 4) NULL,
    [ic_effort_flag]             NVARCHAR (1)    NULL,
    [ic_cost_struct_labor_key]   BIGINT          NULL,
    [ic_apply_billing_markup]    NVARCHAR (1)    NULL,
    [user01]                     NVARCHAR (128)  NULL,
    [user02]                     NVARCHAR (128)  NULL,
    [user03]                     NVARCHAR (128)  NULL,
    [user04]                     NVARCHAR (128)  NULL,
    [user05]                     NVARCHAR (128)  NULL,
    [user06]                     NVARCHAR (128)  NULL,
    [user07]                     NVARCHAR (128)  NULL,
    [user08]                     NVARCHAR (128)  NULL,
    [user09]                     NVARCHAR (128)  NULL,
    [user10]                     NVARCHAR (128)  NULL,
    [ts_sub_po_required]         NVARCHAR (1)    NULL,
    [exp_sub_po_required]        NVARCHAR (1)    NULL,
    [item_assignment_flag]       NVARCHAR (1)    NULL,
    [item_task_required]         NVARCHAR (1)    NULL,
    [pm_approves_before_mgr]     NVARCHAR (1)    NULL,
    [user11]                     NVARCHAR (128)  NULL,
    [user12]                     NVARCHAR (128)  NULL,
    [user13]                     NVARCHAR (128)  NULL,
    [user14]                     NVARCHAR (128)  NULL,
    [user15]                     NVARCHAR (128)  NULL,
    [user16]                     NVARCHAR (128)  NULL,
    [user17]                     NVARCHAR (128)  NULL,
    [user18]                     NVARCHAR (128)  NULL,
    [user19]                     NVARCHAR (128)  NULL,
    [user20]                     NVARCHAR (128)  NULL,
    [advanced_costing_flag]      NVARCHAR (1)    NULL,
    [cost_struct_labor_key]      BIGINT          NULL,
    [created_timestamp]          DATETIME2 (6)   NULL,
    [last_updated_timestamp]     DATETIME2 (6)   NULL,
    [project_currency]           BIGINT          NULL,
    [project_billing_currency]   BIGINT          NULL
);


GO

