CREATE TABLE [dbo].["aretum"."expense_data_allocation"] (
    [expense_data_allocation_key]    BIGINT          NULL,
    [expense_data_key]               BIGINT          NULL,
    [project_key]                    BIGINT          NULL,
    [task_key]                       BIGINT          NULL,
    [allocation]                     DECIMAL (6, 3)  NULL,
    [amount]                         DECIMAL (20, 4) NULL,
    [bill_amount]                    DECIMAL (20, 4) NULL,
    [expense_currency]               NVARCHAR (25)   NULL,
    [sequence]                       INT             NULL,
    [vat_amount]                     DECIMAL (20, 4) NULL,
    [vat_location_key]               BIGINT          NULL,
    [cost_struct_odc_key]            BIGINT          NULL,
    [project_type_key]               BIGINT          NULL,
    [billable]                       NVARCHAR (1)    NULL,
    [post_history_key]               BIGINT          NULL,
    [invoice_key]                    BIGINT          NULL,
    [markup]                         DECIMAL (5, 2)  NULL,
    [cost_account_key]               BIGINT          NULL,
    [cost_post_history_key]          BIGINT          NULL,
    [vendor_invoice_key]             BIGINT          NULL,
    [po_key]                         BIGINT          NULL,
    [po_expense_line_descriptor_key] BIGINT          NULL,
    [ic_cost_struct_odc_key]         BIGINT          NULL,
    [ic_cost_amount]                 DECIMAL (20, 4) NULL,
    [ic_cost_post_history_key]       BIGINT          NULL,
    [ic_revenue_post_history_key]    BIGINT          NULL,
    [local_currency]                 BIGINT          NULL,
    [local_exchange_rate]            DECIMAL (18, 6) NULL,
    [local_amount]                   DECIMAL (20, 4) NULL,
    [local_vat_amount]               DECIMAL (20, 4) NULL,
    [instance_exchange_rate]         DECIMAL (18, 6) NULL,
    [instance_amount]                DECIMAL (20, 4) NULL,
    [instance_vat_amount]            DECIMAL (20, 4) NULL,
    [bill_currency]                  BIGINT          NULL,
    [bill_exchange_rate]             DECIMAL (18, 6) NULL,
    [local_bill_exchange_rate]       DECIMAL (18, 6) NULL,
    [local_bill_amount]              DECIMAL (20, 4) NULL,
    [instance_bill_exchange_rate]    DECIMAL (18, 6) NULL,
    [instance_bill_amount]           DECIMAL (20, 4) NULL,
    [ic_cost_currency]               BIGINT          NULL,
    [local_ic_cost_exchange_rate]    DECIMAL (18, 6) NULL,
    [local_ic_cost_amount]           DECIMAL (20, 4) NULL,
    [instance_ic_cost_exchange_rate] DECIMAL (18, 6) NULL,
    [instance_ic_cost_amount]        DECIMAL (20, 4) NULL,
    [bill_local_exchange_rate]       DECIMAL (18, 6) NULL,
    [instance_local_exchange_rate]   DECIMAL (18, 6) NULL
);


GO

