CREATE TABLE [dbo].["aretum"."person_time_data"] (
    [time_data_key]                  BIGINT           NULL,
    [person_time_key]                BIGINT           NULL,
    [project_key]                    BIGINT           NULL,
    [task_key]                       BIGINT           NULL,
    [work_date]                      DATETIME2 (6)    NULL,
    [quantity]                       DECIMAL (15, 2)  NULL,
    [eff_quantity]                   DECIMAL (25, 12) NULL,
    [bill_customer]                  BIGINT           NULL,
    [cost_customer]                  BIGINT           NULL,
    [pay_code_key]                   BIGINT           NULL,
    [bill_rate]                      DECIMAL (15, 5)  NULL,
    [cost_rate]                      DECIMAL (15, 5)  NULL,
    [eff_bill_rate]                  DECIMAL (15, 5)  NULL,
    [eff_cost_rate]                  DECIMAL (15, 5)  NULL,
    [project_type_key]               BIGINT           NULL,
    [modified_person_key]            BIGINT           NULL,
    [adjusted_number]                BIGINT           NULL,
    [pending_adjustment]             NVARCHAR (1)     NULL,
    [adjusted_head]                  NVARCHAR (1)     NULL,
    [pending_head]                   NVARCHAR (1)     NULL,
    [post_date]                      DATETIME2 (6)    NULL,
    [last_update]                    DATETIME2 (6)    NULL,
    [batch_key]                      BIGINT           NULL,
    [labor_category_key]             BIGINT           NULL,
    [cost_struct_labor_key]          BIGINT           NULL,
    [comments]                       NVARCHAR (2000)  NULL,
    [adjustment_reason]              NVARCHAR (2000)  NULL,
    [location_key]                   BIGINT           NULL,
    [post_history_key]               BIGINT           NULL,
    [invoice_key]                    BIGINT           NULL,
    [cost_post_history_key]          BIGINT           NULL,
    [additional_pay]                 DECIMAL (15, 5)  NULL,
    [vendor_invoice_key]             BIGINT           NULL,
    [po_key]                         BIGINT           NULL,
    [po_labor_line_descriptor_key]   BIGINT           NULL,
    [pilob_post_history_key]         BIGINT           NULL,
    [ic_cost_struct_labor_key]       BIGINT           NULL,
    [ic_cost_rate]                   DECIMAL (15, 5)  NULL,
    [ic_cost_post_history_key]       BIGINT           NULL,
    [ic_revenue_post_history_key]    BIGINT           NULL,
    [ic_eff_cost_rate]               DECIMAL (15, 5)  NULL,
    [rejection_reason]               NVARCHAR (100)   NULL,
    [bill_currency]                  BIGINT           NULL,
    [cost_currency]                  BIGINT           NULL,
    [ic_cost_currency]               BIGINT           NULL,
    [local_bill_exchange_rate]       DECIMAL (18, 6)  NULL,
    [local_cost_exchange_rate]       DECIMAL (18, 6)  NULL,
    [local_ic_cost_exchange_rate]    DECIMAL (18, 6)  NULL,
    [instance_bill_exchange_rate]    DECIMAL (18, 6)  NULL,
    [instance_cost_exchange_rate]    DECIMAL (18, 6)  NULL,
    [instance_ic_cost_exchange_rate] DECIMAL (18, 6)  NULL,
    [source_bill_rate_currency]      BIGINT           NULL,
    [proj_bill_exchange_rate]        DECIMAL (18, 6)  NULL,
    [source_bill_rate]               DECIMAL (15, 5)  NULL,
    [bill_amount]                    DECIMAL (20, 4)  NULL,
    [cost_amount]                    DECIMAL (20, 4)  NULL,
    [ic_cost_amount]                 DECIMAL (20, 4)  NULL,
    [bill_local_exchange_rate]       DECIMAL (18, 6)  NULL,
    [instance_local_exchange_rate]   DECIMAL (18, 6)  NULL
);


GO

