CREATE TABLE [dbo].["aretum"."customer"] (
    [customer_key]                BIGINT         NULL,
    [customer_code]               NVARCHAR (25)  NULL,
    [customer_name]               NVARCHAR (128) NULL,
    [customer_type_key]           BIGINT         NULL,
    [customer_size]               INT            NULL,
    [account_number]              NVARCHAR (25)  NULL,
    [sic_code]                    NVARCHAR (10)  NULL,
    [classification]              NVARCHAR (25)  NULL,
    [industry]                    NVARCHAR (64)  NULL,
    [sector]                      NVARCHAR (64)  NULL,
    [stock_symbol]                NVARCHAR (10)  NULL,
    [url]                         NVARCHAR (128) NULL,
    [active]                      NVARCHAR (1)   NULL,
    [financial_org]               NVARCHAR (1)   NULL,
    [legal_entity]                NVARCHAR (1)   NULL,
    [legal_entity_key]            BIGINT         NULL,
    [default_gl_post_org_key]     BIGINT         NULL,
    [entry_allowed]               NVARCHAR (1)   NULL,
    [begin_date]                  DATETIME2 (6)  NULL,
    [end_date]                    DATETIME2 (6)  NULL,
    [recipient_name_1099]         NVARCHAR (128) NULL,
    [vendor_1099]                 NVARCHAR (1)   NULL,
    [federal_tax_id]              NVARCHAR (9)   NULL,
    [federal_tax_id_type]         SMALLINT       NULL,
    [email_1099]                  NVARCHAR (255) NULL,
    [last_project_code_seq]       BIGINT         NULL,
    [start_with_project_code_seq] BIGINT         NULL,
    [user01]                      NVARCHAR (128) NULL,
    [user02]                      NVARCHAR (128) NULL,
    [user03]                      NVARCHAR (128) NULL,
    [user04]                      NVARCHAR (128) NULL,
    [user05]                      NVARCHAR (128) NULL,
    [user06]                      NVARCHAR (128) NULL,
    [user07]                      NVARCHAR (128) NULL,
    [user08]                      NVARCHAR (128) NULL,
    [user09]                      NVARCHAR (128) NULL,
    [user10]                      NVARCHAR (128) NULL,
    [user11]                      NVARCHAR (128) NULL,
    [user12]                      NVARCHAR (128) NULL,
    [user13]                      NVARCHAR (128) NULL,
    [user14]                      NVARCHAR (128) NULL,
    [user15]                      NVARCHAR (128) NULL,
    [user16]                      NVARCHAR (128) NULL,
    [user17]                      NVARCHAR (128) NULL,
    [user18]                      NVARCHAR (128) NULL,
    [user19]                      NVARCHAR (128) NULL,
    [user20]                      NVARCHAR (128) NULL,
    [transact_elimination_flag]   NVARCHAR (1)   NULL,
    [created_timestamp]           DATETIME2 (6)  NULL,
    [last_updated_timestamp]      DATETIME2 (6)  NULL,
    [currency_code_key]           BIGINT         NULL,
    [default_person_org_flag]     NVARCHAR (1)   NULL,
    [expense_policy_key]          BIGINT         NULL,
    [tax1]                        NVARCHAR (25)  NULL,
    [tax2]                        NVARCHAR (25)  NULL,
    [tax3]                        NVARCHAR (25)  NULL
);


GO

