CREATE TABLE [dbo].["aretum"."expense_type"] (
    [expense_type_key]     BIGINT          NULL,
    [expense_type]         NVARCHAR (25)   NULL,
    [expense_type_name]    NVARCHAR (50)   NULL,
    [description]          NVARCHAR (2000) NULL,
    [threshold]            DECIMAL (20, 4) NULL,
    [vendor_required]      NVARCHAR (1)    NULL,
    [locked]               NVARCHAR (1)    NULL,
    [account_number]       NVARCHAR (2000) NULL,
    [markup]               DECIMAL (5, 2)  NULL,
    [request_allowed]      NVARCHAR (1)    NULL,
    [receipt_required]     NVARCHAR (1)    NULL,
    [show_description]     NVARCHAR (1)    NULL,
    [enabled]              NVARCHAR (1)    NULL,
    [wizard_type]          DECIMAL (2)     NULL,
    [record_overage]       NVARCHAR (1)    NULL,
    [overage_expense_type] BIGINT          NULL,
    [mileage_rate_set_key] BIGINT          NULL,
    [cost_account_key]     BIGINT          NULL,
    [user01]               NVARCHAR (128)  NULL,
    [user02]               NVARCHAR (128)  NULL,
    [user03]               NVARCHAR (128)  NULL,
    [user04]               NVARCHAR (128)  NULL,
    [user05]               NVARCHAR (128)  NULL,
    [user06]               NVARCHAR (128)  NULL,
    [user07]               NVARCHAR (128)  NULL,
    [user08]               NVARCHAR (128)  NULL,
    [user09]               NVARCHAR (128)  NULL,
    [user10]               NVARCHAR (128)  NULL,
    [user11]               NVARCHAR (128)  NULL,
    [user12]               NVARCHAR (128)  NULL,
    [user13]               NVARCHAR (128)  NULL,
    [user14]               NVARCHAR (128)  NULL,
    [user15]               NVARCHAR (128)  NULL,
    [user16]               NVARCHAR (128)  NULL,
    [user17]               NVARCHAR (128)  NULL,
    [user18]               NVARCHAR (128)  NULL,
    [user19]               NVARCHAR (128)  NULL,
    [user20]               NVARCHAR (128)  NULL
);


GO

