CREATE TABLE [dbo].["aretum"."invoice"] (
    [invoice_key]              BIGINT          NULL,
    [invoice_number]           NVARCHAR (50)   NULL,
    [invoice_date]             DATETIME2 (6)   NULL,
    [project_key]              BIGINT          NULL,
    [customer_key]             BIGINT          NULL,
    [billed_organization_key]  BIGINT          NULL,
    [billed_account_key]       BIGINT          NULL,
    [created_by]               BIGINT          NULL,
    [created_date]             DATETIME2 (6)   NULL,
    [completed_by]             BIGINT          NULL,
    [completed_date]           DATETIME2 (6)   NULL,
    [extracted_by]             BIGINT          NULL,
    [extracted_date]           DATETIME2 (6)   NULL,
    [amount]                   DECIMAL (20, 4) NULL,
    [discount_amount]          DECIMAL (20, 4) NULL,
    [billing_through]          DATETIME2 (6)   NULL,
    [payment_term_key]         BIGINT          NULL,
    [due_date]                 DATETIME2 (6)   NULL,
    [discount_date]            DATETIME2 (6)   NULL,
    [contract_number]          NVARCHAR (25)   NULL,
    [order_number]             NVARCHAR (25)   NULL,
    [funded_value]             DECIMAL (17, 4) NULL,
    [company_logo]             BIGINT          NULL,
    [memo]                     NVARCHAR (2000) NULL,
    [description]              NVARCHAR (2000) NULL,
    [show_proj_code]           NVARCHAR (1)    NULL,
    [show_proj_title]          NVARCHAR (1)    NULL,
    [show_proj_funded_value]   NVARCHAR (1)    NULL,
    [show_company_logo]        NVARCHAR (1)    NULL,
    [show_contract_number]     NVARCHAR (1)    NULL,
    [show_order_number]        NVARCHAR (1)    NULL,
    [invoice_format_key]       BIGINT          NULL,
    [voided_invoice_key]       BIGINT          NULL,
    [voiding_invoice_key]      BIGINT          NULL,
    [bill_to_street1]          NVARCHAR (255)  NULL,
    [bill_to_street2]          NVARCHAR (255)  NULL,
    [bill_to_street3]          NVARCHAR (2000) NULL,
    [bill_to_city]             NVARCHAR (60)   NULL,
    [bill_to_state_province]   NVARCHAR (60)   NULL,
    [bill_to_postal_code]      NVARCHAR (16)   NULL,
    [bill_to_country]          NVARCHAR (60)   NULL,
    [ship_to_street1]          NVARCHAR (255)  NULL,
    [ship_to_street2]          NVARCHAR (255)  NULL,
    [ship_to_street3]          NVARCHAR (2000) NULL,
    [ship_to_city]             NVARCHAR (60)   NULL,
    [ship_to_state_province]   NVARCHAR (60)   NULL,
    [ship_to_postal_code]      NVARCHAR (16)   NULL,
    [ship_to_country]          NVARCHAR (60)   NULL,
    [remit_to_street1]         NVARCHAR (255)  NULL,
    [remit_to_street2]         NVARCHAR (255)  NULL,
    [remit_to_street3]         NVARCHAR (2000) NULL,
    [remit_to_city]            NVARCHAR (60)   NULL,
    [remit_to_state_province]  NVARCHAR (60)   NULL,
    [remit_to_postal_code]     NVARCHAR (16)   NULL,
    [remit_to_country]         NVARCHAR (60)   NULL,
    [bill_to_first_name]       NVARCHAR (50)   NULL,
    [bill_to_last_name]        NVARCHAR (50)   NULL,
    [bill_to_middle_initial]   NVARCHAR (1)    NULL,
    [bill_to_suffix]           NVARCHAR (10)   NULL,
    [ship_to_first_name]       NVARCHAR (50)   NULL,
    [ship_to_last_name]        NVARCHAR (50)   NULL,
    [ship_to_middle_initial]   NVARCHAR (1)    NULL,
    [ship_to_suffix]           NVARCHAR (10)   NULL,
    [remit_to_first_name]      NVARCHAR (50)   NULL,
    [remit_to_last_name]       NVARCHAR (50)   NULL,
    [remit_to_middle_initial]  NVARCHAR (1)    NULL,
    [remit_to_suffix]          NVARCHAR (10)   NULL,
    [invoice_option]           NVARCHAR (1)    NULL,
    [show_proj_org_code]       NVARCHAR (1)    NULL,
    [post_date]                DATETIME2 (6)   NULL,
    [emailed_by]               BIGINT          NULL,
    [emailed_timestamp]        DATETIME2 (6)   NULL,
    [printed_by]               BIGINT          NULL,
    [printed_timestamp]        DATETIME2 (6)   NULL,
    [auto_correct_rounding]    NVARCHAR (1)    NULL,
    [historical_data_load_key] BIGINT          NULL,
    [reminder_template_key]    BIGINT          NULL,
    [reminder_frequency]       SMALLINT        NULL,
    [enable_reminder]          NVARCHAR (1)    NULL,
    [allowed_online_payment]   NVARCHAR (1)    NULL,
    [allowed_credit_card]      NVARCHAR (1)    NULL,
    [allowed_ach]              NVARCHAR (1)    NULL,
    [credit_card_min_amount]   DECIMAL (20, 4) NULL,
    [credit_card_max_amount]   DECIMAL (20, 4) NULL,
    [ach_min_amount]           DECIMAL (20, 4) NULL,
    [ach_max_amount]           DECIMAL (20, 4) NULL,
    [billing_from_date]        DATETIME2 (6)   NULL,
    [status]                   NVARCHAR (25)   NULL,
    [submitted_by]             BIGINT          NULL,
    [submitted_timestamp]      DATETIME2 (6)   NULL,
    [controller_key]           BIGINT          NULL,
    [signer_key]               BIGINT          NULL,
    [fee_pass_through]         NVARCHAR (1)    NULL,
    [currency]                 BIGINT          NULL,
    [local_currency]           BIGINT          NULL,
    [local_exchange_rate]      DECIMAL (18, 6) NULL,
    [local_amount]             DECIMAL (20, 4) NULL,
    [instance_exchange_rate]   DECIMAL (18, 6) NULL,
    [instance_amount]          DECIMAL (20, 4) NULL
);


GO

