CREATE TABLE [dbo].["aretum"."purchase_order"] (
    [po_key]            BIGINT          NULL,
    [legal_entity_key]  BIGINT          NULL,
    [pr_key]            BIGINT          NULL,
    [document_number]   NVARCHAR (15)   NULL,
    [po_owner_key]      BIGINT          NULL,
    [owning_org_key]    BIGINT          NULL,
    [amount]            DECIMAL (20, 4) NULL,
    [expected_value]    DECIMAL (20, 4) NULL,
    [reference]         NVARCHAR (25)   NULL,
    [description]       NVARCHAR (128)  NULL,
    [vendor_org_key]    BIGINT          NULL,
    [payment_term_key]  BIGINT          NULL,
    [vi_overage]        NVARCHAR (1)    NULL,
    [document_date]     DATETIME2 (6)   NULL,
    [commitment_date]   DATETIME2 (6)   NULL,
    [begin_date]        DATETIME2 (6)   NULL,
    [end_date]          DATETIME2 (6)   NULL,
    [required_by_date]  DATETIME2 (6)   NULL,
    [purchaser_key]     BIGINT          NULL,
    [project_key]       BIGINT          NULL,
    [task_key]          BIGINT          NULL,
    [internal_comments] VARBINARY (MAX) NULL,
    [external_comments] VARBINARY (MAX) NULL,
    [chain_key]         BIGINT          NULL,
    [controller_key]    BIGINT          NULL,
    [status]            NVARCHAR (25)   NULL,
    [status_timestamp]  DATETIME2 (6)   NULL,
    [orig_po_key]       BIGINT          NULL,
    [mod_number]        SMALLINT        NULL,
    [user01]            NVARCHAR (128)  NULL,
    [user02]            NVARCHAR (128)  NULL,
    [user03]            NVARCHAR (128)  NULL,
    [user04]            NVARCHAR (128)  NULL,
    [user05]            NVARCHAR (128)  NULL,
    [user06]            NVARCHAR (128)  NULL,
    [user07]            NVARCHAR (128)  NULL,
    [user08]            NVARCHAR (128)  NULL,
    [user09]            NVARCHAR (128)  NULL,
    [user10]            NVARCHAR (128)  NULL,
    [user11]            NVARCHAR (128)  NULL,
    [user12]            NVARCHAR (128)  NULL,
    [user13]            NVARCHAR (128)  NULL,
    [user14]            NVARCHAR (128)  NULL,
    [user15]            NVARCHAR (128)  NULL,
    [user16]            NVARCHAR (128)  NULL,
    [user17]            NVARCHAR (128)  NULL,
    [user18]            NVARCHAR (128)  NULL,
    [user19]            NVARCHAR (128)  NULL,
    [user20]            NVARCHAR (128)  NULL,
    [closed_date]       DATETIME2 (6)   NULL,
    [receiver_key]      BIGINT          NULL,
    [emailed_by]        BIGINT          NULL,
    [emailed_timestamp] DATETIME2 (6)   NULL,
    [printed_by]        BIGINT          NULL,
    [printed_timestamp] DATETIME2 (6)   NULL,
    [promised_date]     DATETIME2 (6)   NULL,
    [delivery_date]     DATETIME2 (6)   NULL,
    [contract_key]      BIGINT          NULL,
    [currency_code_key] BIGINT          NULL
);


GO

