CREATE TABLE [dbo].["aretum"."po_format"] (
    [po_format_key]              BIGINT         NULL,
    [name]                       NVARCHAR (50)  NULL,
    [description]                NVARCHAR (128) NULL,
    [active]                     NVARCHAR (1)   NULL,
    [image_setup_key]            BIGINT         NULL,
    [signer_key]                 BIGINT         NULL,
    [po_header_description]      NVARCHAR (128) NULL,
    [summary_proj_show_org_code] NVARCHAR (1)   NULL,
    [summary_proj_show_code]     NVARCHAR (1)   NULL,
    [summary_proj_show_title]    NVARCHAR (1)   NULL,
    [summary_task_show_number]   NVARCHAR (1)   NULL,
    [summary_task_show_name]     NVARCHAR (1)   NULL,
    [detail_proj_show_org_code]  NVARCHAR (1)   NULL,
    [detail_proj_show_code]      NVARCHAR (1)   NULL,
    [detail_proj_show_title]     NVARCHAR (1)   NULL,
    [detail_task_show_number]    NVARCHAR (1)   NULL,
    [detail_task_show_name]      NVARCHAR (1)   NULL,
    [show_external_comments]     NVARCHAR (1)   NULL,
    [show_user01]                NVARCHAR (1)   NULL,
    [show_user02]                NVARCHAR (1)   NULL,
    [show_user03]                NVARCHAR (1)   NULL,
    [show_user04]                NVARCHAR (1)   NULL,
    [show_user05]                NVARCHAR (1)   NULL,
    [show_user06]                NVARCHAR (1)   NULL,
    [show_user07]                NVARCHAR (1)   NULL,
    [show_user08]                NVARCHAR (1)   NULL,
    [show_user09]                NVARCHAR (1)   NULL,
    [show_user10]                NVARCHAR (1)   NULL,
    [show_user11]                NVARCHAR (1)   NULL,
    [show_user12]                NVARCHAR (1)   NULL,
    [show_user13]                NVARCHAR (1)   NULL,
    [show_user14]                NVARCHAR (1)   NULL,
    [show_user15]                NVARCHAR (1)   NULL,
    [show_user16]                NVARCHAR (1)   NULL,
    [show_user17]                NVARCHAR (1)   NULL,
    [show_user18]                NVARCHAR (1)   NULL,
    [show_user19]                NVARCHAR (1)   NULL,
    [show_user20]                NVARCHAR (1)   NULL
);


GO

