CREATE TABLE [dbo].["aretum"."project_note"] (
    [project_note_key]         BIGINT          NULL,
    [project_key]              BIGINT          NULL,
    [creator_person_key]       BIGINT          NULL,
    [modified_person_key]      BIGINT          NULL,
    [project_note_status_key]  BIGINT          NULL,
    [project_note_type_key]    BIGINT          NULL,
    [create_date]              DATETIME2 (6)   NULL,
    [modified_date]            DATETIME2 (6)   NULL,
    [title]                    NVARCHAR (128)  NULL,
    [action_date]              DATETIME2 (6)   NULL,
    [completed_date]           DATETIME2 (6)   NULL,
    [assignee_person_key]      BIGINT          NULL,
    [enforce_role_restriction] NVARCHAR (1)    NULL,
    [note]                     NVARCHAR (2000) NULL,
    [user01]                   NVARCHAR (128)  NULL,
    [user02]                   NVARCHAR (128)  NULL,
    [user03]                   NVARCHAR (128)  NULL,
    [user04]                   NVARCHAR (128)  NULL,
    [user05]                   NVARCHAR (128)  NULL,
    [user06]                   NVARCHAR (128)  NULL,
    [user07]                   NVARCHAR (128)  NULL,
    [user08]                   NVARCHAR (128)  NULL,
    [user09]                   NVARCHAR (128)  NULL,
    [user10]                   NVARCHAR (128)  NULL,
    [user11]                   NVARCHAR (128)  NULL,
    [user12]                   NVARCHAR (128)  NULL,
    [user13]                   NVARCHAR (128)  NULL,
    [user14]                   NVARCHAR (128)  NULL,
    [user15]                   NVARCHAR (128)  NULL,
    [user16]                   NVARCHAR (128)  NULL,
    [user17]                   NVARCHAR (128)  NULL,
    [user18]                   NVARCHAR (128)  NULL,
    [user19]                   NVARCHAR (128)  NULL,
    [user20]                   NVARCHAR (128)  NULL
);


GO

