CREATE TABLE [dbo].["aretum"."project_invoice"] (
    [project_key]            BIGINT          NULL,
    [invoice_option]         NVARCHAR (1)    NULL,
    [invoice_format_key]     BIGINT          NULL,
    [invoice_number_key]     BIGINT          NULL,
    [payment_term_key]       BIGINT          NULL,
    [generate_invoice]       NVARCHAR (1)    NULL,
    [company_logo]           BIGINT          NULL,
    [contract_number]        NVARCHAR (25)   NULL,
    [order_number]           NVARCHAR (25)   NULL,
    [description]            NVARCHAR (2000) NULL,
    [memo]                   NVARCHAR (2000) NULL,
    [show_proj_org_code]     NVARCHAR (1)    NULL,
    [show_proj_code]         NVARCHAR (1)    NULL,
    [show_proj_title]        NVARCHAR (1)    NULL,
    [show_proj_funded_value] NVARCHAR (1)    NULL,
    [show_company_logo]      NVARCHAR (1)    NULL,
    [show_contract_number]   NVARCHAR (1)    NULL,
    [show_order_number]      NVARCHAR (1)    NULL,
    [bill_to_address_key]    BIGINT          NULL,
    [bill_to_contact_key]    BIGINT          NULL,
    [remit_to_address_key]   BIGINT          NULL,
    [remit_to_contact_key]   BIGINT          NULL,
    [ship_to_address_key]    BIGINT          NULL,
    [ship_to_contact_key]    BIGINT          NULL,
    [delivery_option]        NVARCHAR (1)    NULL,
    [email_template_key]     BIGINT          NULL,
    [to_email]               NVARCHAR (255)  NULL,
    [cc_email]               NVARCHAR (255)  NULL,
    [bcc_email]              NVARCHAR (255)  NULL,
    [delivery_receipt_req]   NVARCHAR (1)    NULL,
    [read_receipt_req]       NVARCHAR (1)    NULL,
    [reminder_template_key]  BIGINT          NULL,
    [reminder_frequency]     SMALLINT        NULL,
    [enable_reminder]        NVARCHAR (1)    NULL,
    [allowed_online_payment] NVARCHAR (1)    NULL,
    [allowed_credit_card]    NVARCHAR (1)    NULL,
    [allowed_ach]            NVARCHAR (1)    NULL,
    [credit_card_min_amount] DECIMAL (20, 4) NULL,
    [credit_card_max_amount] DECIMAL (20, 4) NULL,
    [ach_min_amount]         DECIMAL (20, 4) NULL,
    [ach_max_amount]         DECIMAL (20, 4) NULL,
    [signer_key]             BIGINT          NULL,
    [fee_pass_through]       NVARCHAR (1)    NULL
);


GO

