CREATE TABLE [dbo].["aretum"."task"] (
    [task_key]                 BIGINT          NULL,
    [project_key]              BIGINT          NULL,
    [task_id]                  INT             NULL,
    [parent_task]              BIGINT          NULL,
    [task_name]                NVARCHAR (50)   NULL,
    [orig_start_date]          DATETIME2 (6)   NULL,
    [orig_end_date]            DATETIME2 (6)   NULL,
    [rev_start_date]           DATETIME2 (6)   NULL,
    [rev_end_date]             DATETIME2 (6)   NULL,
    [funded_value]             DECIMAL (17, 4) NULL,
    [limit_bill_to_funded]     NVARCHAR (1)    NULL,
    [limit_rev_to_funded]      NVARCHAR (1)    NULL,
    [hours_budget]             DECIMAL (15, 2) NULL,
    [hours_etc]                DECIMAL (15, 2) NULL,
    [hours_est_tot]            DECIMAL (15, 2) NULL,
    [exp_bill_budget]          DECIMAL (17, 4) NULL,
    [exp_cost_budget]          DECIMAL (17, 4) NULL,
    [exp_cost_burden_budget]   DECIMAL (17, 4) NULL,
    [exp_bill_etc]             DECIMAL (17, 4) NULL,
    [exp_cost_etc]             DECIMAL (17, 4) NULL,
    [exp_bill_est_tot]         DECIMAL (17, 4) NULL,
    [exp_cost_est_tot]         DECIMAL (17, 4) NULL,
    [labor_bill_budget]        DECIMAL (17, 4) NULL,
    [labor_cost_budget]        DECIMAL (17, 4) NULL,
    [labor_cost_burden_budget] DECIMAL (17, 4) NULL,
    [labor_bill_etc]           DECIMAL (17, 4) NULL,
    [labor_cost_etc]           DECIMAL (17, 4) NULL,
    [labor_bill_est_tot]       DECIMAL (17, 4) NULL,
    [labor_cost_est_tot]       DECIMAL (17, 4) NULL,
    [output]                   NVARCHAR (50)   NULL,
    [status]                   NVARCHAR (50)   NULL,
    [completed]                DATETIME2 (6)   NULL,
    [url]                      NVARCHAR (128)  NULL,
    [active]                   NVARCHAR (1)    NULL,
    [alertable]                NVARCHAR (1)    NULL,
    [account_code]             NVARCHAR (64)   NULL,
    [sequence]                 INT             NULL,
    [task_number]              NVARCHAR (128)  NULL,
    [indent_level]             INT             NULL,
    [left_visit]               BIGINT          NULL,
    [right_visit]              BIGINT          NULL,
    [percent_complete]         DECIMAL (6, 3)  NULL,
    [duration]                 DECIMAL (5)     NULL,
    [external_id]              BIGINT          NULL,
    [project_type_key]         BIGINT          NULL,
    [billing_type_key]         BIGINT          NULL,
    [owning_customer_key]      BIGINT          NULL,
    [user01]                   NVARCHAR (128)  NULL,
    [user02]                   NVARCHAR (128)  NULL,
    [user03]                   NVARCHAR (128)  NULL,
    [user04]                   NVARCHAR (128)  NULL,
    [user05]                   NVARCHAR (128)  NULL,
    [user06]                   NVARCHAR (128)  NULL,
    [user07]                   NVARCHAR (128)  NULL,
    [user08]                   NVARCHAR (128)  NULL,
    [user09]                   NVARCHAR (128)  NULL,
    [user10]                   NVARCHAR (128)  NULL,
    [time_assignment_flag]     NVARCHAR (1)    NULL,
    [expense_assignment_flag]  NVARCHAR (1)    NULL,
    [ts_sub_po_required]       NVARCHAR (1)    NULL,
    [exp_sub_po_required]      NVARCHAR (1)    NULL,
    [item_assignment_flag]     NVARCHAR (1)    NULL,
    [user11]                   NVARCHAR (128)  NULL,
    [user12]                   NVARCHAR (128)  NULL,
    [user13]                   NVARCHAR (128)  NULL,
    [user14]                   NVARCHAR (128)  NULL,
    [user15]                   NVARCHAR (128)  NULL,
    [user16]                   NVARCHAR (128)  NULL,
    [user17]                   NVARCHAR (128)  NULL,
    [user18]                   NVARCHAR (128)  NULL,
    [user19]                   NVARCHAR (128)  NULL,
    [user20]                   NVARCHAR (128)  NULL,
    [created_timestamp]        DATETIME2 (6)   NULL,
    [created_by]               BIGINT          NULL,
    [last_modified_timestamp]  DATETIME2 (6)   NULL,
    [last_modified_by]         BIGINT          NULL,
    [project_task_sequence]    NVARCHAR (52)   NULL
);


GO

