CREATE TABLE [dbo].["aretum"."contract"] (
    [contract_key]                 BIGINT          NULL,
    [contract_code]                NVARCHAR (50)   NULL,
    [contract_title]               NVARCHAR (2000) NULL,
    [contract_status_key]          BIGINT          NULL,
    [contract_manager_key]         BIGINT          NULL,
    [owning_org_key]               BIGINT          NULL,
    [customer_key]                 BIGINT          NULL,
    [contract_officer]             BIGINT          NULL,
    [end_customer_key]             BIGINT          NULL,
    [prime_or_sub]                 NVARCHAR (1)    NULL,
    [prime_contract_key]           BIGINT          NULL,
    [award_date]                   DATETIME2 (6)   NULL,
    [begin_date]                   DATETIME2 (6)   NULL,
    [end_date]                     DATETIME2 (6)   NULL,
    [contract_purpose]             NVARCHAR (2000) NULL,
    [ceiling_amount]               DECIMAL (17, 4) NULL,
    [sca_rate_flag]                NVARCHAR (1)    NULL,
    [naics_code_key_primary]       BIGINT          NULL,
    [naics_code_key_supporting]    BIGINT          NULL,
    [sbsa_flag]                    NVARCHAR (1)    NULL,
    [sbsa_recertification_date]    DATETIME2 (6)   NULL,
    [business_size_classification] NVARCHAR (1)    NULL,
    [contract_billing_analyst_key] BIGINT          NULL,
    [dcaa_office]                  NVARCHAR (128)  NULL,
    [dpas_purchase_rating]         NVARCHAR (50)   NULL,
    [classified_contract_flag]     NVARCHAR (1)    NULL,
    [usc_restrictions_flag]        NVARCHAR (1)    NULL,
    [security_clearance]           NVARCHAR (1)    NULL,
    [other_clearance]              NVARCHAR (50)   NULL,
    [user01]                       NVARCHAR (128)  NULL,
    [user02]                       NVARCHAR (128)  NULL,
    [user03]                       NVARCHAR (128)  NULL,
    [user04]                       NVARCHAR (128)  NULL,
    [user05]                       NVARCHAR (128)  NULL,
    [user06]                       NVARCHAR (128)  NULL,
    [user07]                       NVARCHAR (128)  NULL,
    [user08]                       NVARCHAR (128)  NULL,
    [user09]                       NVARCHAR (128)  NULL,
    [user10]                       NVARCHAR (128)  NULL,
    [user11]                       NVARCHAR (128)  NULL,
    [user12]                       NVARCHAR (128)  NULL,
    [user13]                       NVARCHAR (128)  NULL,
    [user14]                       NVARCHAR (128)  NULL,
    [user15]                       NVARCHAR (128)  NULL,
    [user16]                       NVARCHAR (128)  NULL,
    [user17]                       NVARCHAR (128)  NULL,
    [user18]                       NVARCHAR (128)  NULL,
    [user19]                       NVARCHAR (128)  NULL,
    [user20]                       NVARCHAR (128)  NULL,
    [currency_code_key]            BIGINT          NULL,
    [funding_required]             NVARCHAR (1)    NULL
);


GO

