CREATE TABLE [dbo].["aretum"."purchase_requisition"] (
    [pr_key]            BIGINT          NULL,
    [legal_entity_key]  BIGINT          NULL,
    [document_number]   NVARCHAR (15)   NULL,
    [document_date]     DATETIME2 (6)   NULL,
    [requestor_key]     BIGINT          NULL,
    [status]            NVARCHAR (25)   NULL,
    [status_timestamp]  DATETIME2 (6)   NULL,
    [chain_key]         BIGINT          NULL,
    [controller_key]    BIGINT          NULL,
    [orig_pr_key]       BIGINT          NULL,
    [mod_number]        SMALLINT        NULL,
    [expected_value]    DECIMAL (20, 4) NULL,
    [required_by_date]  DATETIME2 (6)   NULL,
    [vendor_org_key]    BIGINT          NULL,
    [project_key]       BIGINT          NULL,
    [task_key]          BIGINT          NULL,
    [purchaser_key]     BIGINT          NULL,
    [reference]         NVARCHAR (25)   NULL,
    [description]       NVARCHAR (128)  NULL,
    [internal_comments] NVARCHAR (2000) NULL,
    [external_comments] NVARCHAR (2000) NULL,
    [owning_org_key]    BIGINT          NULL,
    [user01]            NVARCHAR (128)  NULL,
    [user02]            NVARCHAR (128)  NULL,
    [user03]            NVARCHAR (128)  NULL,
    [user04]            NVARCHAR (128)  NULL,
    [user05]            NVARCHAR (128)  NULL,
    [user06]            NVARCHAR (128)  NULL,
    [user07]            NVARCHAR (128)  NULL,
    [user08]            NVARCHAR (128)  NULL,
    [user09]            NVARCHAR (128)  NULL,
    [user10]            NVARCHAR (128)  NULL,
    [po_amount_control] NVARCHAR (1)    NULL,
    [amount]            DECIMAL (20, 4) NULL,
    [user11]            NVARCHAR (128)  NULL,
    [user12]            NVARCHAR (128)  NULL,
    [user13]            NVARCHAR (128)  NULL,
    [user14]            NVARCHAR (128)  NULL,
    [user15]            NVARCHAR (128)  NULL,
    [user16]            NVARCHAR (128)  NULL,
    [user17]            NVARCHAR (128)  NULL,
    [user18]            NVARCHAR (128)  NULL,
    [user19]            NVARCHAR (128)  NULL,
    [user20]            NVARCHAR (128)  NULL,
    [currency_code_key] BIGINT          NULL
);


GO

