CREATE TABLE [dbo].["aretum"."project_budget_history"] (
    [project_budget_history_key] BIGINT          NULL,
    [project_key]                BIGINT          NULL,
    [modified_by]                BIGINT          NULL,
    [modified_date]              DATETIME2 (6)   NULL,
    [orig_start_date]            DATETIME2 (6)   NULL,
    [orig_end_date]              DATETIME2 (6)   NULL,
    [rev_start_date]             DATETIME2 (6)   NULL,
    [rev_end_date]               DATETIME2 (6)   NULL,
    [completed_date]             DATETIME2 (6)   NULL,
    [total_value]                DECIMAL (17, 4) NULL,
    [funded_value]               DECIMAL (17, 4) NULL,
    [hours_budget]               DECIMAL (15, 2) NULL,
    [hours_etc]                  DECIMAL (15, 2) NULL,
    [hours_est_tot]              DECIMAL (15, 2) NULL,
    [exp_bill_budget]            DECIMAL (17, 4) NULL,
    [exp_cost_budget]            DECIMAL (17, 4) NULL,
    [exp_cost_burden_budget]     DECIMAL (17, 4) NULL,
    [exp_bill_etc]               DECIMAL (17, 4) NULL,
    [exp_cost_etc]               DECIMAL (17, 4) NULL,
    [exp_bill_est_tot]           DECIMAL (17, 4) NULL,
    [exp_cost_est_tot]           DECIMAL (17, 4) NULL,
    [labor_bill_budget]          DECIMAL (17, 4) NULL,
    [labor_cost_budget]          DECIMAL (17, 4) NULL,
    [labor_cost_burden_budget]   DECIMAL (17, 4) NULL,
    [labor_bill_etc]             DECIMAL (17, 4) NULL,
    [labor_cost_etc]             DECIMAL (17, 4) NULL,
    [labor_bill_est_tot]         DECIMAL (17, 4) NULL,
    [labor_cost_est_tot]         DECIMAL (17, 4) NULL,
    [probability_percent]        DECIMAL (3)     NULL,
    [percent_complete]           DECIMAL (6, 3)  NULL,
    [pct_complete_rule]          NVARCHAR (1)    NULL,
    [enforce_wbs_dates]          NVARCHAR (1)    NULL,
    [total_cost]                 DECIMAL (17, 4) NULL,
    [total_fee]                  DECIMAL (17, 4) NULL,
    [funded_cost]                DECIMAL (17, 4) NULL,
    [funded_fee]                 DECIMAL (17, 4) NULL,
    [orig_total_value]           DECIMAL (17, 4) NULL,
    [orig_total_cost]            DECIMAL (17, 4) NULL,
    [orig_total_fee]             DECIMAL (17, 4) NULL,
    [orig_funded_value]          DECIMAL (17, 4) NULL,
    [orig_funded_cost]           DECIMAL (17, 4) NULL,
    [orig_funded_fee]            DECIMAL (17, 4) NULL
);


GO

