CREATE TABLE [dbo].["aretum"."fixed_asset"] (
    [fixed_asset_key]            BIGINT          NULL,
    [fixed_asset_number]         NVARCHAR (128)  NULL,
    [serial_number]              NVARCHAR (128)  NULL,
    [name]                       NVARCHAR (128)  NULL,
    [description]                NVARCHAR (2000) NULL,
    [acquisition_date]           DATETIME2 (6)   NULL,
    [acquisition_value]          DECIMAL (20, 4) NULL,
    [disposal_type]              NVARCHAR (1)    NULL,
    [disposal_date]              DATETIME2 (6)   NULL,
    [disposal_value]             DECIMAL (20, 4) NULL,
    [fa_status_key]              BIGINT          NULL,
    [fa_class_key]               BIGINT          NULL,
    [in_service_date]            DATETIME2 (6)   NULL,
    [useful_life]                INT             NULL,
    [salvage_value]              DECIMAL (20, 4) NULL,
    [depreciation_start_date]    DATETIME2 (6)   NULL,
    [depreciation_start_balance] DECIMAL (20, 4) NULL,
    [depreciation_method]        NVARCHAR (1)    NULL,
    [averaging_method]           NVARCHAR (1)    NULL,
    [asset_org_key]              BIGINT          NULL,
    [expense_org_key]            BIGINT          NULL,
    [accum_deprec_org_key]       BIGINT          NULL,
    [legal_entity_key]           BIGINT          NULL,
    [owner_key]                  BIGINT          NULL,
    [user01]                     NVARCHAR (128)  NULL,
    [user02]                     NVARCHAR (128)  NULL,
    [user03]                     NVARCHAR (128)  NULL,
    [user04]                     NVARCHAR (128)  NULL,
    [user05]                     NVARCHAR (128)  NULL,
    [user06]                     NVARCHAR (128)  NULL,
    [user07]                     NVARCHAR (128)  NULL,
    [user08]                     NVARCHAR (128)  NULL,
    [user09]                     NVARCHAR (128)  NULL,
    [user10]                     NVARCHAR (128)  NULL,
    [user11]                     NVARCHAR (128)  NULL,
    [user12]                     NVARCHAR (128)  NULL,
    [user13]                     NVARCHAR (128)  NULL,
    [user14]                     NVARCHAR (128)  NULL,
    [user15]                     NVARCHAR (128)  NULL,
    [user16]                     NVARCHAR (128)  NULL,
    [user17]                     NVARCHAR (128)  NULL,
    [user18]                     NVARCHAR (128)  NULL,
    [user19]                     NVARCHAR (128)  NULL,
    [user20]                     NVARCHAR (128)  NULL
);


GO

