CREATE TABLE [dbo].["SYS"."ReferenceKeyColumns"] (
    [PKTABLE_CAT]   NVARCHAR (255) NULL,
    [PKTABLE_SCHEM] NVARCHAR (255) NULL,
    [PKTABLE_NAME]  NVARCHAR (255) NULL,
    [PKCOLUMN_NAME] NVARCHAR (255) NULL,
    [FKTABLE_CAT]   NVARCHAR (255) NULL,
    [FKTABLE_SCHEM] NVARCHAR (255) NULL,
    [FKTABLE_NAME]  NVARCHAR (255) NULL,
    [FKCOLUMN_NAME] NVARCHAR (255) NULL,
    [KEY_SEQ]       SMALLINT       NULL,
    [UPDATE_RULE]   INT            NULL,
    [DELETE_RULE]   INT            NULL,
    [FK_NAME]       NVARCHAR (255) NULL,
    [PK_NAME]       NVARCHAR (255) NULL,
    [DEFERRABILITY] INT            NULL
);


GO

